select * from INFORMATION_SCHEMA.TABLES

select * from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME='dim_customers'

--Explore all the countries that customers come from
select DISTINCT country from gold.dim_customers

--Explore all categories "the major divisions"
select DISTINCT category,subcategory,product_name from gold.dim_products
order by 1,2,3

--Find the date of first and last order
--How many years of sales available
select min(order_date) first_order_date,
max(order_date) last_order_date,
DATEDIFF(year,MIN(order_date),MAX(order_date)) order_years,
DATEDIFF(month,MIN(order_date),MAX(order_date)) order_months
from gold.fact_sales

--Select the youngest and oldest customer
select min(birthdate) youngest_customer_age,
DATEDIFF(year,min(birthdate),GETDATE()) oldest_customer_age,
max(birthdate) oldest_customer_age,
DATEDIFF(year,max(birthdate),GETDATE()) youngest_customer_age
from gold.dim_customers

--Find the total Sales
select sum(sales_amount) total_sales from gold.fact_sales

--How many items are sold
select sum(quantity) total_quantity from gold.fact_sales

--Find the average selling price
select avg(price) average_price from gold.fact_sales

--Find total no of orders
select count(distinct order_number) as total_orders from gold.fact_sales

--Find total no of products
select count(product_number) as total_products from gold.dim_products

--Find total no of customers
select count(customer_number) as total_customers from gold.dim_customers

--Find total no of customers that have placed atleast one order
select count(distinct customer_key) as total_customers from gold.dim_customers

--Generate a report showing all key metrices
select 'Total Sales' as measure_name ,sum(sales_amount) as measure_value from gold.fact_sales
union all
select 'Total Quantity',sum(quantity) from gold.fact_sales
union all 
select 'Average Price',avg(price) from gold.fact_sales
union all
select 'Total Orders',count(distinct order_number) from gold.fact_sales
union all
select 'Total Products',count(product_number) from gold.dim_products
union all 
select 'Total Customers',count(customer_number) as total_customers from gold.dim_customers


--Total customers by country
select country,count(customer_key) total_customers 
from gold.dim_customers
group by (country)
order by total_customers desc

--Total Customers by Gender
select gender,count(customer_key) total_customers 
from gold.dim_customers
group by (gender)
order by total_customers desc

--Total Products by Category
select category,count(product_key) total_products 
from gold.dim_products
group by (category)
order by total_products desc

--Average cost in each category
Select category,AVG(cost) average_cost
from gold.dim_products
group by (category)
order by average_cost

--Total cost for each category
Select category,sum(cost) total_cost
from gold.dim_products
group by (category)
order by total_cost

--Total Revenue Generated by each category
select p.category,sum(f.sales_amount) total_revenue 
from gold.fact_sales f
left join gold.dim_products p
on p.product_key=f.product_key
group by p.category
order by total_revenue

--What is the distribution of sold item across countries
select c.country,sum(f.quantity) sold_items
from gold.dim_customers c
left join gold.fact_sales f
on c.customer_key=f.customer_key
group by c.country
order by sold_items

--Which 5 products generate the hightest revenue
select * from (
select p.product_name,sum(f.sales_amount) total_revenue, 
ROW_NUMBER() over(order by sum(f.sales_amount)desc) rank
from gold.fact_sales f
left join gold.dim_products p
on p.product_key=f.product_key
group by p.product_name) t
where rank <=5

--Which 5 products generate the lowest revenue
select Top 5 p.product_name,sum(f.sales_amount) total_revenue
from gold.fact_sales f
left join gold.dim_products p
on p.product_key=f.product_key
group by p.product_name
order by total_revenue

--Find the top 10 customers who have generated the highest revenue
Select top 10 c.customer_key,c.first_name,c.last_name,sum(f.sales_amount) total_revenue
from gold.fact_sales f
left join gold.dim_customers c
on c.customer_key=f.customer_key
group by c.customer_key,c.first_name,c.last_name
order by total_revenue desc

--Find top 3 customers with fewest orders placed
Select top 3 c.customer_key,c.first_name,c.last_name,count(distinct f.order_number) total_orders
from gold.fact_sales f
left join gold.dim_customers c
on c.customer_key=f.customer_key
group by c.customer_key,c.first_name,c.last_name
order by total_orders 